#!/bin/bash

# copy Atmospheric turbulence simulation scripts to local directory
execname=cacao

srcdir=$( $execname -i| grep SOURCEDIR| awk '{ print $NF }')


currdir=$( pwd )
echo "Current directory : $currdir"
echo "Source directory  : $srcdir" 



for sname in runturb mkHVturbprof
do
rm $sname 2> /dev/null
ln -s $srcdir/src/AtmosphericTurbulence/scripts/$sname $currdir/$sname
done

